name: shared_flutter_components_sqart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  skeleton_text: ^3.0.0
  flutter_translate: ^4.0.3
  pattern_formatter: ^2.0.0
  country_code_picker:
    git:
      url: https://github.com/square-art/CountryCodePicker
      ref: master
  dropdown_button2:
    git:
      url: https://github.com/square-art/dropdown_button2
      ref: master
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

